{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbird.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | default .Values.global.domain | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | default .Values.global.domain | quote }}
      http:
        paths:
          {{- if .Values.ingress.dashboard.path }}
          - path: {{ .Values.ingress.dashboard.path }}
            pathType: {{ .Values.ingress.dashboard.pathType }}
            backend:
              service:
                name: {{ include "netbird.fullname" . }}-dashboard
                port:
                  number: {{ .Values.dashboard.service.http.port }}
          {{- end }}
          {{/*
          {{- if .Values.ingress.management.path }}
          - path: {{ .Values.ingress.management.path }}
            pathType: {{ .Values.ingress.management.pathType }}
            backend:
              service:
                name: {{ include "netbird.fullname" . }}-management
                port:
                  number: {{ .Values.management.service.port }}
          {{- end }}
          */}}
{{- end }}